name: my first workflow1
on:
  workflow_dispatch:
    
  push:
    branches:
      - main
env:
  message: Hi I am Raju
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one line script
        run: echo $message
